// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abectcmtyeahpnzolrct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiZWN0Y210eWVhaHBuem9scmN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyMjg3NjEsImV4cCI6MjA4ODgwNDc2MX0.MlTcFLWDWv2YP4pJbSXI7ICPyghNKfEDnlVCJTiHTHI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});