// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncztasjalmanuowmqqko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jenRhc2phbG1hbnVvd21xcWtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MTUyMzEsImV4cCI6MjA3NDQ5MTIzMX0.ZFH7fzMYdyp3Mx_GDTcxSxnlE7-bCyNo-vqZAhNA2Pc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});